datadog:
  apiKeyExistingSecret: datadog-secret
  tags:
    - env:dev
  logs:
    enabled: true
    containerCollectAll: false
    containerCollectUsingFiles: true
  kubelet:
    host:
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    hostCAPath: /etc/kubernetes/certs/kubeletserver.crt
  serviceMonitoring:
    enabled: true
agents:
  env:
    # (...)
    - name: DD_DOGSTATSD_SOCKET
      value: "/var/run/datadog/dsd.socket"
    - name: DD_DOGSTATSD_ORIGIN_DETECTION
      value: 'true'
  volumeMounts:
      - name: dsdsocket
        mountPath: /var/run/datadog
      ##...
  volumes:
      - hostPath:
            path: /var/run/datadog/
        name: dsdsocket
dogstatsd:
  port: 8125
  # useHostPort: true
  # nonLocalTraffic: true
  
